### ISSUE TITLE
Update ASpace EAD export to include "title" for all name-title entries

### ISSUE THREAD

**Issue by lorawoodford** [Smithsonian/lassb-ead-exporter#8]
See https://aspace.si.edu/resources/28711

Two name-title entries, but neither are serialized in the EAD, so they can't be treated properly in the metadata pipeline.

First step is just to add to the EAD exports.   Both EAD2002 and EAD3 (which will have those part elements to clearly separate the parts)

Seems like this should be added to a plugin locally for now, while also submitted as a core code pull request (due to standardization, yeah!)

Subsequent tickets will be required to manage the metadata flow.

**Comment by fordmadox** [comment]
As illustrated in https://github.com/Smithsonian/lassb-ead-exporter/pull/7, my original proposed mapping needs refinement, since MARC Relator codes can also be added for those name-title entries in ASpace.
